[package]
name = "orbutils"
description = "The Orbital Utilities"
repository = "https://github.com/redox-os/orbutils"
version = "0.1.16"
license-file = "LICENSE"
readme = "README.md"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[[bin]]
name = "background"
path = "src/background/main.rs"

[[bin]]
name = "browser"
path = "src/browser/main.rs"

[[bin]]
name = "calculator"
path = "src/calculator/main.rs"

[[bin]]
name = "character_map"
path = "src/character_map/main.rs"

[[bin]]
name = "editor"
path = "src/editor/main.rs"

[[bin]]
name = "file_manager"
path = "src/file_manager/main.rs"

[[bin]]
name = "launcher"
path = "src/launcher/main.rs"

[[bin]]
name = "orblogin"
path = "src/orblogin/main.rs"

[[bin]]
name = "viewer"
path = "src/viewer/main.rs"

[[bin]]
name = "calendar"
path = "src/calendar/main.rs"

[dependencies]
calculate = "0.1.*"
chrono = "0.4"
html5ever = "0.15"
hyper-rustls = "0.6"
mime_guess = "1.8"
mime = "0.2"
orbclient = "0.3"
orbfont = "0.1"
orbimage = "0.1"
orbtk = "0.2"
tendril = "0.4"
url = "1.5"
userutils = { git = "https://github.com/redox-os/userutils.git" }

[dependencies.hyper]
version = "0.10"
default-features = false

[target.'cfg(not(target_os = "redox"))'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_event = { git = "https://github.com/redox-os/event.git" }
redox_syscall = "0.1"
